from django.urls import path
from . import views
from . import views_map
from . import views_waypoints
from .views_filebrowser import file_browse
from geocaches import views_tasks

app_name = "geocaches"

urlpatterns = [
    path("", views.cache_list, name="list"),
    path("map/markers/", views_map.map_markers, name="map_markers"),
    path("map/waypoints/", views_map.map_waypoints, name="map_waypoints"),
    path("map/areas/", views_map.saved_areas_list, name="saved_areas_list"),
    path("map/areas/save/", views_map.saved_area_save, name="saved_area_save"),
    path("map/areas/<int:pk>/delete/", views_map.saved_area_delete, name="saved_area_delete"),
    path("map/providers/", views_map.map_providers, name="map_providers"),
    path("map/quota/", views_map.map_quota, name="map_quota"),
    path("map/preview/", views_map.map_preview, name="map_preview"),
    path("map/preview/<str:task_id>/", views_map.map_preview_result, name="map_preview_result"),
    path("map/sync/", views_map.map_sync, name="map_sync"),
    path("map/auto-enrich/", views_map.map_auto_enrich, name="map_auto_enrich"),
    path("browse/", file_browse, name="file_browse"),
    path("export/gpx/", views.cache_export_gpx, name="export_gpx"),
    path("export/gpx/recent-folders/", views.export_recent_folders, name="export_recent_folders"),
    path("import/gpx/", views.import_gpx, name="import_gpx"),
    path("import/gpx/detect/", views.detect_gpx_format_ajax, name="detect_gpx_format"),
    path("import/gsak/", views.import_gsak, name="import_gsak"),
    path("import/lab2gpx/", views.import_lab2gpx, name="import_lab2gpx"),
    path("import/fieldnotes/", views.import_fieldnotes, name="import_fieldnotes"),
    path("logs/bulk/", views.bulk_logging, name="bulk_logging"),
    path("import/gsak-locations/", views.import_gsak_locations, name="import_gsak_locations"),
    path("pq/", views.pq_management, name="pq_management"),
    path("pq/list.json", views.pq_list_json, name="pq_list_json"),
    path("pq/match-preview.json", views.pq_match_preview, name="pq_match_preview"),
    path("delete/", views.cache_delete_filtered, name="delete_filtered"),
    path("delete/progress/", views.cache_delete_progress, name="delete_progress"),
    path("tools/remove-zero-waypoints/", views.tools_remove_zero_waypoints, name="tools_remove_zero_waypoints"),
    path("tools/duped-my-logs/", views.tools_duped_my_logs, name="tools_duped_my_logs"),
    path("tools/duped-cache-logs/", views.tools_duped_cache_logs, name="tools_duped_cache_logs"),
    path("tools/misplaced-codes/", views.tools_misplaced_codes, name="tools_misplaced_codes"),
    path("tools/duplicate-caches/", views.tools_duplicate_caches, name="tools_duplicate_caches"),
    path("tools/manage-fused/", views.tools_manage_fused, name="tools_manage_fused"),
    path("tools/unlinked-oc/", views.tools_unlinked_oc, name="tools_unlinked_oc"),
    path("tools/check-ftf/", views.tools_check_ftf, name="tools_check_ftf"),
    path("tools/ftf-markers/", views.tools_ftf_markers, name="tools_ftf_markers"),
    path("tools/ftf-verify/<int:pk>/", views.ftf_verify_row, name="ftf_verify_row"),
    path("tools/event-calendar/", views.tools_event_calendar, name="tools_event_calendar"),
    path("tools/event-calendar/<int:pk>/ical/", views.tools_event_ical, name="tools_event_ical"),
    path("enrich/", views.cache_enrich, name="enrich"),
    path("enrich/status/", views.enrich_status, name="enrich_status"),
    path("enrich/cancel/", views.enrich_cancel, name="enrich_cancel"),
    path("update/", views.cache_update, name="update"),
    path("update/status/", views.update_status, name="update_status"),
    path("update/cancel/", views.update_cancel, name="update_cancel"),
    path("tasks/status/", views_tasks.task_status, name="task_status"),
    path("tasks/<str:task_id>/", views_tasks.task_status_json, name="task_status_json"),
    path("tags/", views.tag_management, name="tags"),
    path("tags/json/", views.tags_json, name="tags_json"),
    path("tags/bulk-add/", views.bulk_tag_add, name="bulk_tag_add"),
    path("tags/bulk-remove/", views.bulk_tag_remove, name="bulk_tag_remove"),
    path("filters/save/", views.saved_filter_save, name="filter_save"),
    path("filters/<int:pk>/delete/", views.saved_filter_delete, name="filter_delete"),
    path("where-clauses/save/", views.where_clause_save, name="where_save"),
    path("where-clauses/<int:pk>/delete/", views.where_clause_delete, name="where_delete"),
    path("<str:gc_code>/", views.cache_detail, name="detail"),
    path("<str:gc_code>/fetch-logs/", views.cache_fetch_logs, name="fetch_logs"),
    path("<str:gc_code>/refresh/", views.cache_refresh, name="refresh"),
    path("<str:gc_code>/toggle-lock/", views.cache_toggle_lock, name="toggle_lock"),
    path("<str:gc_code>/defuse/", views.cache_defuse, name="defuse"),
    path("<str:gc_code>/delete/", views.cache_delete, name="delete"),
    path("<str:gc_code>/corrected/", views.corrected_coords_save, name="corrected_save"),
    path("<str:gc_code>/map-state/save/", views.save_map_state, name="save_map_state"),
    path("<str:gc_code>/map-state/reset/", views.reset_map_state, name="reset_map_state"),
    path("<str:gc_code>/set-refpoint/", views.set_as_reference_point, name="set_refpoint"),
    path("<str:gc_code>/tags/", views.cache_tag_edit, name="tag_edit"),
    path("<str:gc_code>/log/submit/", views.log_submit, name="log_submit"),
    path("<str:gc_code>/oc-passphrase/", views.oc_passphrase_save, name="oc_passphrase_save"),
    path("<str:gc_code>/waypoints/add/", views_waypoints.waypoint_save, name="waypoint_add"),
    path("<str:gc_code>/waypoints/<int:wp_id>/edit/", views_waypoints.waypoint_save, name="waypoint_edit"),
    path("<str:gc_code>/waypoints/<int:wp_id>/hide/", views_waypoints.waypoint_hide, name="waypoint_hide"),
    path("<str:gc_code>/waypoints/<int:wp_id>/unhide/", views_waypoints.waypoint_unhide, name="waypoint_unhide"),
    path("<str:gc_code>/waypoints/<int:wp_id>/complete/", views_waypoints.waypoint_toggle_complete, name="waypoint_complete"),
    path("<str:gc_code>/waypoints/restore-hidden/", views_waypoints.waypoint_restore_all, name="waypoint_restore_all"),
    path("<str:gc_code>/waypoints/<int:wp_id>/delete/", views_waypoints.waypoint_delete, name="waypoint_delete"),
    path("<str:gc_code>/notes/add/", views.note_add, name="note_add"),
    path("logs/<int:log_id>/delete/", views.log_delete, name="log_delete"),
    path("notes/<int:note_id>/update/", views.note_update, name="note_update"),
    path("notes/<int:note_id>/delete/", views.note_delete, name="note_delete"),
]
