from django.urls import path
from .views import bulk as views_bulk
from .views import cache_actions as views_cache_actions
from .views import calendar as views_calendar
from .views import dashboard as views_dashboard
from .views import detail as views_detail
from .views import export as views_export
from .views import gps as views_gps
from .views import imports as views_imports
from .views import list as views_list
from .views import notes_logs as views_notes_logs
from .views import notifications as views_notifications
from .views import pq as views_pq
from .views import saved_filters as views_saved_filters
from .views import tags as views_tags
from .views import tools_compare_profiles as views_tools_compare_profiles
from .views import tools_dedup as views_tools_dedup
from .views import tools_events as views_tools_events
from .views import tools_ftf as views_tools_ftf
from .views import tools_fused as views_tools_fused
from .views import tools_image_gallery as views_tools_image_gallery
from .views import trash as views_trash
from .views import ignore_lists as views_ignore_lists
from .views import map as views_map
from .views import trackables as views_trackables
from .views import trackable_detail as views_trackable_detail
from .views import trackable_list as views_trackable_list
from .views import waypoints as views_waypoints
from .views import task_status as views_tasks
from .views import cached_images as views_cached_images
from .views.filebrowser import file_browse

app_name = "geocaches"

urlpatterns = [
    path("", views_list.cache_list, name="list"),
    path("filters/dialog-options/", views_list.filter_dialog_options, name="filter_dialog_options"),
    path("dashboard/", views_dashboard.dashboard, name="dashboard"),
    path("dashboard/latest-additions/", views_dashboard.dashboard_latest_additions, name="dashboard_latest_additions"),
    path("dashboard/statistics/", views_dashboard.dashboard_statistics, name="dashboard_statistics"),
    path("dashboard/alc/", views_dashboard.dashboard_alc, name="dashboard_alc"),
    path("dashboard/maps/", views_dashboard.dashboard_maps_panel, name="dashboard_maps_panel"),
    path("dashboard/stats/tables/", views_dashboard.dashboard_stat_tables, name="dashboard_stat_tables"),
    path("dashboard/stats/table/", views_dashboard.dashboard_stat_table, name="dashboard_stat_table"),
    path("dashboard/missing/", views_dashboard.dashboard_missing, name="dashboard_missing"),
    path("dashboard/bearing/", views_dashboard.dashboard_bearing_data, name="dashboard_bearing_data"),
    path("dashboard/alc-theme/", views_dashboard.dashboard_alc_theme, name="dashboard_alc_theme"),
    path("dashboard/360/", views_dashboard.dashboard_360_data, name="dashboard_360_data"),
    path("dashboard/360/missing/", views_dashboard.dashboard_360_missing, name="dashboard_360_missing"),
    path("dashboard/360/grid/", views_dashboard.dashboard_360_grid, name="dashboard_360_grid"),
    path("dashboard/360/set-location/", views_dashboard.dashboard_360_set_location, name="dashboard_360_set_location"),
    path("dashboard/souvenirs/list/", views_dashboard.dashboard_souvenirs_list, name="dashboard_souvenirs_list"),
    path("dashboard/souvenirs/refresh/", views_dashboard.dashboard_souvenirs_refresh, name="dashboard_souvenirs_refresh"),
    path("dashboard/souvenirs/tag-editor/", views_dashboard.dashboard_souvenirs_tag_editor, name="dashboard_souvenirs_tag_editor"),
    path("dashboard/souvenirs/set-tags/", views_dashboard.dashboard_souvenirs_set_tags, name="dashboard_souvenirs_set_tags"),
    path("dashboard/souvenirs/tags/", views_dashboard.dashboard_souvenirs_tags_manage, name="dashboard_souvenirs_tags_manage"),
    path("dashboard/treasures/list/", views_dashboard.dashboard_treasures_list, name="dashboard_treasures_list"),
    path("dashboard/treasures/refresh/", views_dashboard.dashboard_treasures_refresh, name="dashboard_treasures_refresh"),
    path("dashboard/treasures/candidates/", views_dashboard.dashboard_treasures_candidates, name="dashboard_treasures_candidates"),
    path("dashboard/treasures/detail/", views_dashboard.dashboard_treasures_detail, name="dashboard_treasures_detail"),
    path("dashboard/region/<str:iso2>/", views_dashboard.dashboard_region_data, name="dashboard_region_data"),
    path("dashboard/county/<str:iso2>/", views_dashboard.dashboard_county_data, name="dashboard_county_data"),
    path("dashboard/district/<str:iso2>/<str:state>/", views_dashboard.dashboard_district_data, name="dashboard_district_data"),
    path("dashboard/region-flag/<str:code>/", views_dashboard.dashboard_region_flag, name="dashboard_region_flag"),
    path("dashboard/calendar/agenda/", views_calendar.calendar_agenda, name="calendar_agenda"),
    path("dashboard/calendar/sync-events/", views_calendar.calendar_sync_events, name="calendar_sync_events"),
    path("dashboard/calendar/add-missing/", views_calendar.calendar_add_missing, name="calendar_add_missing"),
    path("dashboard/calendar/remove-missing/", views_calendar.calendar_remove_missing, name="calendar_remove_missing"),
    path("dashboard/calendar/clear/", views_calendar.calendar_clear, name="calendar_clear"),
    path("dashboard/calendar/candidates/", views_calendar.calendar_day_candidates, name="calendar_day_candidates"),
    path("dashboard/calendar/<int:pk>/alarm/", views_calendar.calendar_toggle_alarm, name="calendar_toggle_alarm"),
    path("dashboard/calendar/<int:pk>/delete/", views_calendar.calendar_delete_entry, name="calendar_delete_entry"),
    path("calendar/<str:token>/gcforge.ics", views_calendar.calendar_feed, name="calendar_feed"),
    path("map/markers/", views_map.map_markers, name="map_markers"),
    path("map/waypoints/", views_map.map_waypoints, name="map_waypoints"),
    path("map/route/", views_map.map_route, name="map_route"),
    path("map/routes/", views_map.saved_routes_list, name="saved_routes_list"),
    path("map/routes/save/", views_map.saved_route_save, name="saved_route_save"),
    path("map/routes/<int:pk>/delete/", views_map.saved_route_delete, name="saved_route_delete"),
    path("map/areas/", views_map.saved_areas_list, name="saved_areas_list"),
    path("map/areas/save/", views_map.saved_area_save, name="saved_area_save"),
    path("map/areas/<int:pk>/delete/", views_map.saved_area_delete, name="saved_area_delete"),
    path("map/providers/", views_map.map_providers, name="map_providers"),
    path("map/quota/", views_map.map_quota, name="map_quota"),
    path("map/preview/", views_map.map_preview, name="map_preview"),
    path("map/preview/<str:task_id>/", views_map.map_preview_result, name="map_preview_result"),
    path("map/sync/", views_map.map_sync, name="map_sync"),
    path("map/auto-enrich/", views_map.map_auto_enrich, name="map_auto_enrich"),
    path("map/al-fetch-circles/", views_map.map_al_fetch_circles, name="map_al_fetch_circles"),
    path("map/al-refresh-bbox/", views_map.map_al_refresh_bbox, name="map_al_refresh_bbox"),
    path("browse/", file_browse, name="file_browse"),
    path("cached-images/proxy/", views_cached_images.cached_image_proxy, name="cached_image_proxy"),
    path("cached-images/download-missing/", views_cached_images.download_missing_images, name="download_missing_images"),
    path("cached-images/download-missing-trackables/", views_cached_images.download_missing_trackable_images, name="download_missing_trackable_images"),
    path("export/gpx/", views_export.cache_export_gpx, name="export_gpx"),
    path("export/gpx/recent-folders/", views_export.export_recent_folders, name="export_recent_folders"),
    path("gps/send/", views_gps.send_to_gps, name="send_to_gps"),
    path("gps/recent/", views_gps.gps_recent_devices, name="gps_recent_devices"),
    path("gps/detect/", views_gps.gps_detect_devices, name="gps_detect_devices"),
    path("import/gpx/", views_imports.import_gpx, name="import_gpx"),
    path("import/by-code/", views_imports.import_by_code, name="import_by_code"),
    path("import/by-code-list/", views_imports.import_by_code_list, name="import_by_code_list"),
    path("import/by-code-list/status/<str:task_id>/", views_imports.import_by_code_list_status, name="import_by_code_list_status"),
    path("import/by-list-generation/", views_imports.import_by_list_generation, name="import_by_list_generation"),
    path("import/by-list-generation/status/<str:task_id>/", views_imports.import_by_list_generation_status, name="import_by_list_generation_status"),
    path("import/alc-from-url/", views_imports.import_alc_from_url, name="import_alc_from_url"),
    path("import/gpx/detect/", views_imports.detect_gpx_format_ajax, name="detect_gpx_format"),
    path("import/gsak/", views_imports.import_gsak, name="import_gsak"),
    path("import/lab2gpx/", views_imports.import_lab2gpx, name="import_lab2gpx"),
    path("import/al-founds/", views_imports.import_al_founds, name="import_al_founds"),
    path("import/al-founds/preview/", views_imports.import_al_founds_preview, name="import_al_founds_preview"),
    path("import/al-founds/status/<str:task_id>/", views_imports.import_al_founds_status, name="import_al_founds_status"),
    path("import/al-stage-dates/", views_imports.sync_al_stage_dates, name="sync_al_stage_dates"),
    path("import/al-stage-dates/status/<str:task_id>/", views_imports.sync_al_stage_dates_status, name="sync_al_stage_dates_status"),
    path("import/al-recover-founds/", views_imports.import_al_recover_founds, name="import_al_recover_founds"),
    path("import/al-recover-founds/status/<str:task_id>/", views_imports.import_al_recover_founds_status, name="import_al_recover_founds_status"),
    path("import/fieldnotes/", views_imports.import_fieldnotes, name="import_fieldnotes"),
    path("logs/bulk/", views_bulk.bulk_logging, name="bulk_logging"),
    path("import/gsak-locations/", views_imports.import_gsak_locations, name="import_gsak_locations"),
    path("pq/", views_pq.pq_management, name="pq_management"),
    path("pq/list.json", views_pq.pq_list_json, name="pq_list_json"),
    path("pq/rows.json", views_pq.pq_rows_json, name="pq_rows_json"),
    path("pq/match-preview.json", views_pq.pq_match_preview, name="pq_match_preview"),
    path("pq/split-preview.json", views_pq.pq_split_preview, name="pq_split_preview"),
    path("pq/apply-split.json", views_pq.pq_apply_split, name="pq_apply_split"),
    path("pq/web/", views_pq.pq_management_web, name="pq_management_web"),
    path("pq/web/status/<str:task_id>/", views_pq.pq_web_status, name="pq_web_status"),
    path("notify/", views_notifications.notifications_page, name="notifications"),
    path("notify/sync/", views_notifications.notifications_sync, name="notifications_sync"),
    path("notify/apply-diff/", views_notifications.notifications_apply_diff, name="notifications_apply_diff"),
    path("notify/bulk-create/", views_notifications.notifications_bulk_create, name="notifications_bulk_create"),
    path("notify/region/set-enabled/", views_notifications.notifications_region_set_enabled, name="notifications_region_set_enabled"),
    path("notify/region/delete/", views_notifications.notifications_region_delete, name="notifications_region_delete"),
    path("notify/region/unlink/", views_notifications.notifications_region_unlink, name="notifications_region_unlink"),
    path("notify/region/pull/", views_notifications.notifications_region_pull, name="notifications_region_pull"),
    path("notify/region/push/", views_notifications.notifications_region_push, name="notifications_region_push"),
    path("notify/alt-emails.json", views_notifications.notifications_alt_emails, name="notifications_alt_emails"),
    path("notify/map/circles.json", views_notifications.notifications_map_circles, name="notifications_map_circles"),
    path("notify/oc/<str:platform>/pull/", views_notifications.oc_notification_pull, name="oc_notification_pull"),
    path("notify/oc/<str:platform>/save-globals/", views_notifications.oc_notification_save_globals, name="oc_notification_save_globals"),
    path("notify/oc/<str:platform>/new-nbh/", views_notifications.oc_neighbourhood_create, name="oc_neighbourhood_create"),
    path("notify/oc/<int:pk>/push/", views_notifications.oc_notification_push, name="oc_notification_push"),
    path("notify/oc/<int:pk>/save/", views_notifications.oc_notification_save, name="oc_notification_save"),
    path("notify/oc/<int:pk>/delete/", views_notifications.oc_neighbourhood_delete, name="oc_neighbourhood_delete"),
    path("notify/<int:pk>/toggle/", views_notifications.notification_toggle, name="notification_toggle"),
    path("notify/<int:pk>/delete/", views_notifications.notification_delete, name="notification_delete"),
    path("notify/<int:pk>/unlink/", views_notifications.notification_unlink, name="notification_unlink"),
    path("notify/<int:pk>/edit/", views_notifications.notification_edit, name="notification_edit"),
    path("notify/<int:pk>/set-location/", views_notifications.notification_set_location, name="notification_set_location"),
    path("notify/<int:pk>/pull/", views_notifications.notification_pull, name="notification_pull"),
    path("notify/<int:pk>/push/", views_notifications.notification_push, name="notification_push"),
    path("delete/", views_cache_actions.cache_delete_filtered, name="delete_filtered"),
    path("delete/progress/", views_cache_actions.cache_delete_progress, name="delete_progress"),
    path("trash/", views_trash.trash_list, name="trash"),
    path("trash/empty/", views_trash.trash_empty, name="trash_empty"),
    path("trash/<int:pk>/restore/", views_trash.trash_restore, name="trash_restore"),
    path("trash/<int:pk>/purge/", views_trash.trash_purge, name="trash_purge"),
    path("cache/<str:code>/map-visibility/", views_cache_actions.set_map_visibility, name="cache_map_visibility"),
    path("bulk/map-visibility/", views_bulk.bulk_map_visibility, name="bulk_map_visibility"),
    path("tools/image-gallery/", views_tools_image_gallery.tools_image_gallery_config, name="tools_image_gallery_config"),
    path("tools/image-gallery/generate/", views_tools_image_gallery.tools_image_gallery_generate, name="tools_image_gallery_generate"),
    path("tools/image-gallery/<str:task_id>/", views_tools_image_gallery.tools_image_gallery_view, name="tools_image_gallery_view"),
    path("tools/image-gallery/<str:task_id>/export/html/", views_tools_image_gallery.tools_image_gallery_export_html, name="tools_image_gallery_export_html"),
    path("tools/image-gallery/<str:task_id>/export/odf/", views_tools_image_gallery.tools_image_gallery_export_odf, name="tools_image_gallery_export_odf"),
    path("tools/ignore-lists/", views_ignore_lists.page, name="tools_ignore_lists"),
    path("tools/ignore-lists/add/", views_ignore_lists.add, name="ignore_lists_add"),
    path("tools/ignore-lists/remove/", views_ignore_lists.remove, name="ignore_lists_remove"),
    path("tools/ignore-lists/edit-notes/<int:pk>/", views_ignore_lists.edit_notes, name="ignore_lists_edit_notes"),
    path("tools/ignore-lists/remove-archived/", views_ignore_lists.remove_archived, name="ignore_lists_remove_archived"),
    path("tools/ignore-lists/import-gsak/", views_ignore_lists.import_gsak, name="ignore_lists_import_gsak"),
    path("tools/ignore-lists/import-gsak/preview/", views_ignore_lists.import_gsak_preview, name="ignore_lists_import_gsak_preview"),
    path("tools/ignore-lists/sync-gc/", views_ignore_lists.sync_gc, name="ignore_lists_sync_gc"),
    path("tools/ignore-lists/sync-oc/", views_ignore_lists.sync_oc, name="ignore_lists_sync_oc"),
    path("tools/ignore-lists/refresh/", views_ignore_lists.refresh, name="ignore_lists_refresh"),
    path("tools/ignore-lists/remove-filtered/", views_ignore_lists.remove_filtered, name="ignore_lists_remove_filtered"),
    path("tools/ignore-lists/bulk-transfer/", views_ignore_lists.bulk_transfer, name="ignore_lists_bulk_transfer"),
    path("tools/remove-zero-waypoints/", views_imports.tools_remove_zero_waypoints, name="tools_remove_zero_waypoints"),
    path("tools/duped-my-logs/", views_tools_dedup.tools_duped_my_logs, name="tools_duped_my_logs"),
    path("tools/duped-cache-logs/", views_tools_dedup.tools_duped_cache_logs, name="tools_duped_cache_logs"),
    path("tools/misplaced-codes/", views_tools_dedup.tools_misplaced_codes, name="tools_misplaced_codes"),
    path("tools/duplicate-caches/", views_tools_dedup.tools_duplicate_caches, name="tools_duplicate_caches"),
    path("tools/compare-profiles/", views_tools_compare_profiles.tools_compare_profiles, name="tools_compare_profiles"),
    path("tools/manage-fused/", views_tools_fused.tools_manage_fused, name="tools_manage_fused"),
    path("tools/unlinked-oc/", views_tools_fused.tools_unlinked_oc, name="tools_unlinked_oc"),
    path("tools/check-ftf/", views_tools_ftf.tools_check_ftf, name="tools_check_ftf"),
    path("tools/ftf-markers/", views_tools_ftf.tools_ftf_markers, name="tools_ftf_markers"),
    path("tools/ftf-verify/<int:pk>/", views_tools_ftf.ftf_verify_row, name="ftf_verify_row"),
    path("tools/event-calendar/", views_tools_events.tools_event_calendar, name="tools_event_calendar"),
    path("tools/event-calendar/<int:pk>/ical/", views_tools_events.tools_event_ical, name="tools_event_ical"),
    path("tools/remove-unattended-past-events/", views_tools_events.tools_remove_unattended_past_events, name="tools_remove_unattended_past_events"),
    path("enrich/", views_cache_actions.cache_enrich, name="enrich"),
    path("enrich/status/", views_cache_actions.enrich_status, name="enrich_status"),
    path("enrich/cancel/", views_cache_actions.enrich_cancel, name="enrich_cancel"),
    path("update/", views_cache_actions.cache_update, name="update"),
    path("update/status/", views_cache_actions.update_status, name="update_status"),
    path("update/cancel/", views_cache_actions.update_cancel, name="update_cancel"),
    path("tasks/status/", views_tasks.task_status, name="task_status"),
    path("tasks/<str:task_id>/", views_tasks.task_status_json, name="task_status_json"),
    path("tags/", views_tags.tag_management, name="tags"),
    path("tags/json/", views_tags.tags_json, name="tags_json"),
    path("tags/bulk-add/", views_tags.bulk_tag_add, name="bulk_tag_add"),
    path("tags/bulk-remove/", views_tags.bulk_tag_remove, name="bulk_tag_remove"),
    path("filters/<int:pk>/delete/", views_saved_filters.saved_filter_delete, name="filter_delete"),
    path("filters/tree/apply/", views_saved_filters.tree_filter_apply, name="tree_filter_apply"),
    path("filters/tree/save/", views_saved_filters.tree_filter_save, name="tree_filter_save"),
    path("where-clauses/save/", views_saved_filters.where_clause_save, name="where_save"),
    path("where-clauses/<int:pk>/delete/", views_saved_filters.where_clause_delete, name="where_delete"),
    # Trackables — literal paths must come before the <str:gc_code> catchall.
    path("trackables/", views_trackable_list.trackable_list, name="trackable_list"),
    path("trackables/split/", views_trackable_list.trackable_split, name="trackable_split"),
    path("trackables/map/", views_trackable_list.trackable_map, name="trackable_map"),
    path("trackables/map/pins/", views_trackable_list.trackable_map_pins, name="trackable_map_pins"),
    path("trackables/sync/plan/", views_trackable_list.trackable_sync_plan, name="trackable_sync_plan"),
    path("trackables/sync/one/", views_trackable_list.trackable_sync_one, name="trackable_sync_one"),
    path("trackables/refresh-filtered/plan/", views_trackable_list.trackable_refresh_filtered_plan, name="trackable_refresh_filtered_plan"),
    path("trackables/sync/resolve-locations/", views_trackable_list.trackable_resolve_locations, name="trackable_resolve_locations"),
    path("trackables/sync/codes/plan/", views_trackable_list.trackable_tracking_codes_plan, name="trackable_tracking_codes_plan"),
    path("trackables/sync/codes/one/", views_trackable_list.trackable_tracking_code_fetch, name="trackable_tracking_code_fetch"),
    path("trackables/inventory/", views_trackables.trackable_inventory, name="trackable_inventory"),
    path("trackables/verify/", views_trackables.trackable_verify, name="trackable_verify"),
    path("trackables/log-by-code/", views_trackables.trackable_log_by_code, name="trackable_log_by_code"),
    path("trackables/auto-visit/", views_trackables.trackable_auto_visit_save, name="trackable_auto_visit_save"),
    path("trackables/<str:ref>/", views_trackable_detail.trackable_detail, name="trackable_detail"),
    path("trackables/<str:ref>/refresh/", views_trackable_detail.trackable_refresh, name="trackable_refresh"),
    path("trackables/<str:ref>/action/", views_trackable_detail.trackable_action, name="trackable_action"),
    path("trackables/<str:ref>/coords/", views_trackable_detail.trackable_coords_save, name="trackable_coords_save"),
    path("trackables/<str:ref>/tags/",   views_trackable_detail.trackable_tags_save, name="trackable_tags_save"),
    path("trackables/<str:ref>/tracking/", views_trackable_detail.trackable_tracking_code_save, name="trackable_tracking_code_save"),
    path("trackables/<str:ref>/delete/", views_trackable_detail.trackable_delete, name="trackable_delete"),
    path("<str:gc_code>/", views_detail.cache_detail, name="detail"),
    path("<str:gc_code>/fetch-logs/", views_cache_actions.cache_fetch_logs, name="fetch_logs"),
    path("<str:gc_code>/fetch-al-logs/", views_cache_actions.al_fetch_logs, name="al_fetch_logs"),
    path("<str:gc_code>/export/gpx/", views_export.cache_detail_export_gpx, name="detail_export_gpx"),
    path("<str:gc_code>/refresh/", views_cache_actions.cache_refresh, name="refresh"),
    path("<str:gc_code>/toggle-lock/", views_cache_actions.cache_toggle_lock, name="toggle_lock"),
    path("<str:gc_code>/set-found-accuracy/", views_cache_actions.cache_set_found_accuracy, name="set_found_accuracy"),
    path("<str:gc_code>/location-options/", views_cache_actions.cache_location_options, name="cache_location_options"),
    path("<str:gc_code>/save-location/", views_cache_actions.cache_save_location, name="cache_save_location"),
    path("<str:gc_code>/update-location-from-point/", views_cache_actions.cache_update_location_from_point, name="update_location_from_point"),
    path("<str:gc_code>/update-elevation-from-point/", views_cache_actions.cache_update_elevation_from_point, name="update_elevation_from_point"),
    path("<str:gc_code>/ignore/", views_ignore_lists.cache_ignore, name="cache_ignore"),
    path("<str:gc_code>/unignore/", views_ignore_lists.cache_unignore, name="cache_unignore"),
    path("<str:gc_code>/defuse/", views_cache_actions.cache_defuse, name="defuse"),
    path("<str:gc_code>/delete/", views_cache_actions.cache_delete, name="delete"),
    path("<str:gc_code>/corrected/", views_notes_logs.corrected_coords_save, name="corrected_save"),
    path("<str:gc_code>/map-state/save/", views_cache_actions.save_map_state, name="save_map_state"),
    path("<str:gc_code>/map-state/reset/", views_cache_actions.reset_map_state, name="reset_map_state"),
    path("<str:gc_code>/set-refpoint/", views_cache_actions.set_as_reference_point, name="set_refpoint"),
    path("<str:gc_code>/tags/", views_tags.cache_tag_edit, name="tag_edit"),
    path("<str:gc_code>/log/submit/", views_notes_logs.log_submit, name="log_submit"),
    path("<str:gc_code>/oc-passphrase/", views_notes_logs.oc_passphrase_save, name="oc_passphrase_save"),
    path("<str:gc_code>/al-answer/", views_detail.al_answer_save, name="al_answer_save"),
    path("<str:gc_code>/waypoints/add/", views_waypoints.waypoint_save, name="waypoint_add"),
    path("<str:gc_code>/waypoints/<int:wp_id>/edit/", views_waypoints.waypoint_save, name="waypoint_edit"),
    path("<str:gc_code>/waypoints/<int:wp_id>/hide/", views_waypoints.waypoint_hide, name="waypoint_hide"),
    path("<str:gc_code>/waypoints/<int:wp_id>/unhide/", views_waypoints.waypoint_unhide, name="waypoint_unhide"),
    path("<str:gc_code>/waypoints/<int:wp_id>/complete/", views_waypoints.waypoint_toggle_complete, name="waypoint_complete"),
    path("<str:gc_code>/waypoints/restore-hidden/", views_waypoints.waypoint_restore_all, name="waypoint_restore_all"),
    path("<str:gc_code>/waypoints/<int:wp_id>/delete/", views_waypoints.waypoint_delete, name="waypoint_delete"),
    path("<str:gc_code>/notes/add/", views_notes_logs.note_add, name="note_add"),
    path("logs/<int:log_id>/delete/", views_notes_logs.log_delete, name="log_delete"),
    path("notes/<int:note_id>/update/", views_notes_logs.note_update, name="note_update"),
    path("notes/<int:note_id>/delete/", views_notes_logs.note_delete, name="note_delete"),
]
