# Generated by Django 6.0.3 on 2026-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gc', 'geocaching.com'), ('oc_de', 'opencaching.de'), ('oc_pl', 'opencaching.pl'), ('oc_uk', 'opencaching.uk'), ('oc_nl', 'opencaching.nl'), ('oc_us', 'opencaching.us')], max_length=20)),
                ('user_id', models.CharField(blank=True, help_text='Stable platform-assigned numeric/UUID identifier (preferred for ownership matching)', max_length=50)),
                ('username', models.CharField(help_text='Login name at time of entry — informational, may change', max_length=100)),
                ('label', models.CharField(blank=True, help_text='Display label; defaults to username@platform if empty', max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected in per-account filters; does not restrict ownership detection')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('consumer_key', models.CharField(blank=True, help_text='OKAPI consumer key (public, register at <node>/okapi/signup.html)', max_length=200)),
                ('membership_level', models.IntegerField(default=0, help_text='GC membership level: 0=Unknown, 1=Basic, 2=Charter, 3=Premium')),
            ],
            options={
                'ordering': ['platform', 'username'],
                'unique_together': {('platform', 'user_id')},
            },
        ),
    ]
