# Generated by Django 6.0.3 on 2026-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alc_column_preset_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineMapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bbox_min_lon', models.FloatField()),
                ('bbox_min_lat', models.FloatField()),
                ('bbox_max_lon', models.FloatField()),
                ('bbox_max_lat', models.FloatField()),
                ('min_zoom', models.IntegerField(default=8)),
                ('max_zoom', models.IntegerField(default=16)),
                ('source_url', models.CharField(max_length=500)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tile_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('ready', 'Ready'), ('error', 'Error'), ('updating', 'Updating')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
