# Generated by Django 6.0.4 on 2026-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_offlinemaparea'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('scope', models.CharField(choices=[('any', 'Any log type'), ('Found it', 'Found it'), ("Didn't find it", "Didn't find it"), ('Write note', 'Write note'), ('Needs Maintenance', 'Needs Maintenance'), ('Will Attend', 'Will Attend'), ('Attended', 'Attended'), ('Webcam Photo Taken', 'Webcam Photo Taken')], default='any', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scope', 'name'],
            },
        ),
    ]
