from django.urls import path, re_path
from . import views, views_offline, views_fonts

app_name = "preferences"

urlpatterns = [
    path("settings/",                         views.settings_view,          name="settings"),
    path("settings/save-prefs/",              views.save_prefs,             name="save_prefs"),
    path("settings/save-logging-prefs/",      views.save_logging_prefs,     name="save_logging_prefs"),
    path("settings/save-gc-username/",        views.save_gc_username,       name="save_gc_username"),
    path("settings/fetch-gc-public-guid/",    views.fetch_gc_public_guid,   name="fetch_gc_public_guid"),
    path("settings/save-al-prefs/",           views.save_al_prefs,          name="save_al_prefs"),
    path("settings/save-map-display/",        views.save_map_display,       name="save_map_display"),
    path("settings/save-dashboard-maps/",     views.save_dashboard_maps,    name="save_dashboard_maps"),
    path("settings/save-dashboard-stats/",    views.save_dashboard_stats,   name="save_dashboard_stats"),
    path("settings/download-boundary/",       views.download_boundary,       name="download_boundary"),
    path("settings/update-all-boundaries/",   views.update_all_boundaries,   name="update_all_boundaries"),
    path("settings/save-enrich/",             views.save_enrich,            name="save_enrich"),
    path("settings/enrich-offline/",          views.enrich_locations_offline, name="enrich_locations_offline"),
    path("settings/save-cache-detail/",       views.save_cache_detail,      name="save_cache_detail"),
    path("settings/save-list-view/",          views.save_list_view,         name="save_list_view"),
    path("settings/save-map-state/",          views.save_map_state,         name="save_map_state"),
    path("settings/locations-json/",          views.locations_json,         name="locations_json"),
    path("settings/add-preset/",              views.add_preset,             name="add_preset"),
    path("settings/delete-preset/",          views.delete_preset,          name="delete_preset"),
    path("settings/add-log-template/",        views.add_log_template,       name="add_log_template"),
    path("settings/delete-log-template/",     views.delete_log_template,    name="delete_log_template"),
    path("settings/refresh-total-finds/",     views.refresh_total_finds,    name="refresh_total_finds"),
    path("settings/add-refpoint/",            views.add_refpoint,           name="add_refpoint"),
    path("settings/edit-refpoint/",           views.edit_refpoint,          name="edit_refpoint"),
    path("settings/delete-refpoint/",         views.delete_refpoint,        name="delete_refpoint"),
    path("settings/set-default-refpoint/",    views.set_default_refpoint,   name="set_default_refpoint"),
    path("settings/save-backup-prefs/",       views.save_backup_prefs,      name="save_backup_prefs"),
    path("settings/vacuum-now/",              views.vacuum_now,             name="vacuum_now"),
    path("settings/backup-now/",              views.backup_now,             name="backup_now"),
    path("location/current/",                  views.set_current_location,   name="set_current_location"),
    path("location/save/",                     views.save_location_json,     name="save_location_json"),
    path("scope/",                            views.set_scope,              name="set_scope"),
    path("log/",                               views.log_view,               name="log"),
    path("backup/download/<str:filename>/",   views.backup_download,        name="backup_download"),
    path("backup/restore/",                   views.backup_restore,         name="backup_restore"),
    path("backup/delete/",                    views.backup_delete,          name="backup_delete"),
    path("settings/save-gpx-export/",          views.save_gpx_export,        name="save_gpx_export"),
    path("settings/gpx-export-preset/add/",   views.add_gpx_export_preset,  name="add_gpx_export_preset"),
    path("settings/gpx-export-preset/delete/", views.delete_gpx_export_preset, name="delete_gpx_export_preset"),
    path("settings/gpx-export-preset/load/",  views.load_gpx_export_preset, name="load_gpx_export_preset"),
    path("settings/reset-gpx-export/",        views.reset_gpx_export,       name="reset_gpx_export"),
    path("settings/switch-database/",         views.switch_database,        name="switch_database"),
    path("settings/create-database/",         views.create_database,        name="create_database"),
    path("profile/",                          views.user_profile,           name="user_profile"),
    path("about/",                            views.about_view,             name="about"),
    path("settings/save-offline-prefs/",     views.save_offline_prefs,     name="save_offline_prefs"),
    path("settings/save-image-cache/",       views.save_image_cache_prefs, name="save_image_cache_prefs"),
    path("settings/clear-image-cache/",      views.clear_image_cache,      name="clear_image_cache"),
    path("offline-maps/areas.json",              views_offline.areas_json,      name="offline_areas_json"),
    path("offline-maps/areas-partial",           views_offline.areas_partial,   name="offline_areas_partial"),
    path("offline-maps/<int:pk>/tiles.pmtiles",  views_offline.serve_pmtiles,   name="serve_pmtiles"),
    path("offline-maps/<int:pk>/download",       views_offline.start_download,  name="offline_start_download"),
    path("offline-maps/<int:pk>/delete",         views_offline.delete_area,     name="offline_delete_area"),
    path("offline-maps/create",                  views_offline.create_area,     name="offline_create_area"),
    path("offline-maps/estimate",                views_offline.estimate_tiles,  name="offline_estimate_tiles"),
    re_path(r"^fonts/(?P<fontstack>[^/]+)/(?P<range_str>\d+-\d+)\.pbf$",
            views_fonts.serve_map_glyph, name="map_font_glyph"),
]
