# Generated by Django 6.0.3 on 2026-04-08 23:09

import django.db.migrations.operations.special
import django.db.models.deletion
from datetime import datetime, time, timezone
from django.db import migrations, models


# --- ported RunPython functions ---

def backfill_has_corrected_coordinates(apps, schema_editor):
    Geocache = apps.get_model("geocaches", "Geocache")
    CorrectedCoordinates = apps.get_model("geocaches", "CorrectedCoordinates")
    ids = CorrectedCoordinates.objects.values_list("geocache_id", flat=True)
    Geocache.objects.filter(pk__in=ids).update(has_corrected_coordinates=True)


_TO_GO_SQL = (
    "found = 0 AND completed = 0 AND status = 'Active'"
    " AND NOT (cache_type IN ('Mystery', 'Math/Physics') AND has_corrected_coordinates = 0)"
)

_FTF_POSSIBLE_SQL = (
    "found = 0 AND completed = 0 AND status = 'Active'"
    " AND NOT EXISTS ("
    "SELECT 1 FROM geocaches_log"
    " WHERE geocaches_log.geocache_id = geocaches_geocache.id"
    " AND geocaches_log.log_type IN ('Found it', 'Attended', 'Webcam Photo Taken')"
    ")"
)


def create_builtin_filters(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.update_or_create(
        name="To-go",
        defaults={"params": {"where_sql": _TO_GO_SQL}, "is_builtin": True},
    )
    SavedFilter.objects.update_or_create(
        name="FTF possible",
        defaults={"params": {"where_sql": _FTF_POSSIBLE_SQL}, "is_builtin": True},
    )


def remove_builtin_filters(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.filter(name__in=["To-go", "FTF possible"], is_builtin=True).delete()


def update_ftf_filter(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.update_or_create(
        name="FTF possible",
        defaults={"params": {"flag": "ftf_possible"}, "is_builtin": True},
    )


def revert_ftf_filter(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.update_or_create(
        name="FTF possible",
        defaults={"params": {"where_sql": _FTF_POSSIBLE_SQL}, "is_builtin": True},
    )


def backfill_logged_at(apps, schema_editor):
    Log = apps.get_model("geocaches", "Log")
    logs = Log.objects.filter(logged_at__isnull=True, logged_date__isnull=False)
    batch = []
    for log in logs.iterator(chunk_size=2000):
        log.logged_at = datetime.combine(log.logged_date, time.min, tzinfo=timezone.utc)
        batch.append(log)
        if len(batch) >= 2000:
            Log.objects.bulk_update(batch, ["logged_at"])
            batch = []
    if batch:
        Log.objects.bulk_update(batch, ["logged_at"])


_FUSED_SQL = "gc_code != '' AND oc_code != ''"


def create_fused_filter(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.update_or_create(
        name="Fused (GC+OC)",
        defaults={"params": {"where_sql": _FUSED_SQL}, "is_builtin": True},
    )


def remove_fused_filter(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.filter(name="Fused (GC+OC)", is_builtin=True).delete()


_NOT_UPDATED_TODAY_SQL = "date(updated_at) < date('now')"


def create_not_updated_today_filter(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.update_or_create(
        name="Not updated today",
        defaults={"params": {"where_sql": _NOT_UPDATED_TODAY_SQL}, "is_builtin": True},
    )


def remove_not_updated_today_filter(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.filter(name="Not updated today", is_builtin=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gc', 'geocaching.com'), ('oc', 'opencaching.de')], default='gc', max_length=2)),
                ('attribute_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_positive', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('source', 'attribute_id', 'is_positive')},
            },
        ),
        migrations.CreateModel(
            name='Geocache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('oc_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('cache_type', models.CharField(choices=[('Traditional', 'Traditional'), ('Multi', 'Multi'), ('Mystery', 'Mystery'), ('EarthCache', 'EarthCache'), ('Letterbox', 'Letterbox'), ('Wherigo', 'Wherigo'), ('Event', 'Event'), ('MegaEvent', 'Mega Event'), ('GigaEvent', 'Giga Event'), ('CITO', 'Cache In Trash Out Event'), ('Virtual', 'Virtual'), ('Webcam', 'Webcam'), ('Other', 'Other')], max_length=50)),
                ('size', models.CharField(choices=[('Nano', 'Nano'), ('Micro', 'Micro'), ('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large'), ('XLarge', 'X-Large'), ('NotChosen', 'Not Chosen'), ('Other', 'Other'), ('Virtual', 'Virtual')], default='NotChosen', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('terrain', models.FloatField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('hidden_date', models.DateField(blank=True, null=True)),
                ('last_found_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(blank=True, related_name='geocaches', to='geocaches.attribute')),
                ('tags', models.ManyToManyField(blank=True, related_name='geocaches', to='geocaches.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectedCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geocache', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrected_coordinates', to='geocaches.geocache')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geocaches.geocache')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('Found it', 'Found it'), ("Didn't find it", "Didn't find it"), ('Write note', 'Write note'), ('Needs Maintenance', 'Needs Maintenance'), ('Owner Maintenance', 'Owner Maintenance'), ('Temporarily Disable Listing', 'Temporarily Disable Listing'), ('Enable Listing', 'Enable Listing'), ('Archive', 'Archive'), ('Attended', 'Attended'), ('Webcam Photo Taken', 'Webcam Photo Taken')], max_length=50)),
                ('finder', models.CharField(blank=True, max_length=255)),
                ('logged_date', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('source_id', models.CharField(blank=True, max_length=50)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='geocaches.geocache')),
            ],
            options={
                'ordering': ['-logged_date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='geocaches.geocache')),
            ],
        ),
        migrations.CreateModel(
            name='OCExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('recommendations', models.IntegerField(default=0)),
                ('needs_maintenance', models.BooleanField(default=False)),
                ('trip_time', models.FloatField(blank=True, null=True)),
                ('trip_distance', models.FloatField(blank=True, null=True)),
                ('req_passwd', models.BooleanField(default=False)),
                ('preview_image_url', models.URLField(blank=True, max_length=500)),
                ('geocache', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oc_extension', to='geocaches.geocache')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoint_type', models.CharField(choices=[('Parking', 'Parking Area'), ('Stage', 'Stage of a Multi-Cache'), ('Question', 'Question to Answer'), ('Final', 'Final Location'), ('Trailhead', 'Trailhead'), ('Reference', 'Reference Point'), ('Other', 'Other')], default='Other', max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('lookup', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_user_created', models.BooleanField(default=False)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='geocaches.geocache')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='geocaches.geocache')),
            ],
            options={
                'unique_together': {('geocache', 'key')},
            },
        ),
        migrations.AddConstraint(
            model_name='geocache',
            constraint=models.CheckConstraint(condition=models.Q(('gc_code__gt', ''), ('oc_code__gt', ''), _connector='OR'), name='geocache_has_at_least_one_code'),
        ),
        migrations.AddField(
            model_name='geocache',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geocaches.geocache'),
        ),
        migrations.AddField(
            model_name='geocache',
            name='size_override',
            field=models.CharField(blank=True, choices=[('Nano', 'Nano'), ('Micro', 'Micro'), ('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large'), ('XLarge', 'X-Large'), ('Virtual', 'Virtual'), ('Other', 'Other'), ('Unknown', 'Unknown'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geocache',
            name='size',
            field=models.CharField(choices=[('Nano', 'Nano'), ('Micro', 'Micro'), ('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large'), ('XLarge', 'X-Large'), ('Virtual', 'Virtual'), ('Other', 'Other'), ('Unknown', 'Unknown'), ('None', 'None')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='geocache',
            name='status',
            field=models.CharField(choices=[('Unpublished', 'Unpublished'), ('Active', 'Active'), ('Disabled', 'Disabled'), ('Locked', 'Locked'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='geocache',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='geocache',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='geocache',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='dnf_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='elevation_user',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='fav_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='found_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geocache',
            name='found_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='ftf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='gc_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='has_trackable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='import_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='last_gpx_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='platform_log_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geocache',
            name='user_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='user_sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='watch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='owner_gc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='placed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('adventure_guid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('stage_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_answer_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_journal_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_stage_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name='geocache',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='stage_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geocache',
            name='cache_type',
            field=models.CharField(choices=[('Traditional', 'Traditional'), ('Multi-Cache', 'Multi-Cache'), ('Mystery', 'Mystery'), ('Virtual', 'Virtual'), ('Letterbox Hybrid', 'Letterbox Hybrid'), ('Earthcache', 'Earthcache'), ('Event', 'Event'), ('CITO', 'Cache In Trash Out Event'), ('Webcam', 'Webcam'), ('Wherigo', 'Wherigo'), ('Adventure Lab', 'Adventure Lab'), ('Mega-Event', 'Mega-Event'), ('Giga-Event', 'Giga-Event'), ('Locationless', 'Locationless (Reverse) Cache'), ('GPS Adventures Exhibit', 'GPS Adventures Exhibit'), ('Community Celebration Event', 'Community Celebration Event'), ('Geocaching HQ', 'Geocaching HQ'), ('Geocaching HQ Celebration', 'Geocaching HQ Celebration'), ('Geocaching HQ Block Party', 'Geocaching HQ Block Party'), ('Project A.P.E.', 'Project A.P.E.'), ('NGS Benchmark', 'NGS Benchmark'), ('Drive-In', 'Drive-In Cache'), ('Math/Physics', 'Math/Physics Cache'), ('Moving', 'Moving Cache'), ('Own', 'Own Cache'), ('Podcast', 'Podcast Cache'), ('Unknown', 'Unknown')], max_length=50),
        ),
        migrations.AddField(
            model_name='geocache',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='geocaches.adventure'),
        ),
        migrations.CreateModel(
            name='CacheMapState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.SmallIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geocache', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_state', to='geocaches.geocache')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='default_ref_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tags', to='preferences.referencepoint'),
        ),
        migrations.AddField(
            model_name='geocache',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='note',
            name='body_html',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='body_text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('note', 'Note'), ('field_note', 'Field note')], default='note', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='format',
            field=models.CharField(choices=[('plain', 'Plain text (UTF-8)'), ('html', 'HTML'), ('md', 'Markdown')], default='plain', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='logged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='primary_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='geocache',
            name='needs_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocache',
            name='recommendations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='finder_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ocextension',
            name='recommendations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='iso_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('Found it', 'Found it'), ("Didn't find it", "Didn't find it"), ('Write note', 'Write note'), ('Will Attend', 'Will Attend'), ('Attended', 'Attended'), ('Webcam Photo Taken', 'Webcam Photo Taken'), ('Needs Maintenance', 'Needs Maintenance'), ('Owner Maintenance', 'Owner Maintenance'), ('Update Coordinates', 'Update Coordinates'), ('Temporarily Disable Listing', 'Temporarily Disable Listing'), ('Enable Listing', 'Enable Listing'), ('Publish Listing', 'Publish Listing'), ('Retract Listing', 'Retract Listing'), ('Archive', 'Archive'), ('Permanently Archived', 'Permanently Archived'), ('Needs Archived', 'Needs Archived'), ('Unarchive', 'Unarchive'), ('Post Reviewer Note', 'Post Reviewer Note'), ('Announcement', 'Announcement'), ('submit for review', 'Submit for Review'), ('OC Team comment', 'OC Team Comment')], max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='log_type',
            field=models.CharField(blank=True, choices=[('Found it', 'Found it'), ("Didn't find it", "Didn't find it"), ('Write note', 'Write note'), ('Will Attend', 'Will Attend'), ('Attended', 'Attended'), ('Webcam Photo Taken', 'Webcam Photo Taken'), ('Needs Maintenance', 'Needs Maintenance'), ('Owner Maintenance', 'Owner Maintenance'), ('Update Coordinates', 'Update Coordinates'), ('Temporarily Disable Listing', 'Temporarily Disable Listing'), ('Enable Listing', 'Enable Listing'), ('Publish Listing', 'Publish Listing'), ('Retract Listing', 'Retract Listing'), ('Archive', 'Archive'), ('Permanently Archived', 'Permanently Archived'), ('Needs Archived', 'Needs Archived'), ('Unarchive', 'Unarchive'), ('Post Reviewer Note', 'Post Reviewer Note'), ('Announcement', 'Announcement'), ('submit for review', 'Submit for Review'), ('OC Team comment', 'OC Team Comment')], max_length=50),
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedWhereClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sql', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='ocextension',
            name='attribution_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ocextension',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ocextension',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SavedAreaFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('regions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('bearing_deg', models.FloatField()),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocaches.geocache')),
                ('ref_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.referencepoint')),
            ],
            options={
                'indexes': [models.Index(fields=['ref_point', 'distance_km'], name='geocaches_d_ref_poi_cd846c_idx')],
                'unique_together': {('geocache', 'ref_point')},
            },
        ),
        migrations.AddField(
            model_name='geocache',
            name='has_corrected_coordinates',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=backfill_has_corrected_coordinates,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='SyncQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('used', models.IntegerField(default=0)),
                ('limit', models.IntegerField()),
            ],
            options={
                'unique_together': {('platform', 'mode', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('last_synced', models.DateTimeField()),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('sync_mode', models.CharField(blank=True, max_length=10)),
                ('sync_error', models.CharField(blank=True, max_length=500)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='geocaches.geocache')),
            ],
            options={
                'unique_together': {('geocache', 'platform')},
            },
        ),
        migrations.AlterModelOptions(
            name='savedfilter',
            options={'ordering': ['is_builtin', 'name']},
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=create_builtin_filters,
            reverse_code=remove_builtin_filters,
        ),
        migrations.AlterField(
            model_name='geocache',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geocache',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geocache',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=update_ftf_filter,
            reverse_code=revert_ftf_filter,
        ),
        migrations.AddField(
            model_name='geocache',
            name='background_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-logged_at', '-logged_date']},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='finder_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='finder',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='log',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='logged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=backfill_logged_at,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_fused_filter,
            reverse_code=remove_fused_filter,
        ),
        migrations.AddField(
            model_name='note',
            name='bulk_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='submit_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocextension',
            name='passphrase',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='bulk_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='draft_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='geocache',
            name='user_favorited',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocextension',
            name='user_recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='geocache',
            name='geocache_has_at_least_one_code',
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='geocache',
            constraint=models.CheckConstraint(condition=models.Q(('gc_code__gt', ''), ('oc_code__gt', ''), ('al_code__gt', ''), _connector='OR'), name='geocache_has_at_least_one_code'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_user_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CacheFusionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_code', models.CharField(db_index=True, max_length=20)),
                ('oc_code', models.CharField(db_index=True, max_length=20)),
                ('auto_linked', models.BooleanField(default=False)),
                ('user_decision', models.CharField(blank=True, choices=[('fuse', 'Fuse'), ('dont_fuse', "Don't fuse"), ('postpone', 'Postpone')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('gc_code', 'oc_code')},
            },
        ),
        migrations.AddField(
            model_name='ocextension',
            name='related_gc_code',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocache',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=create_not_updated_today_filter,
            reverse_code=remove_not_updated_today_filter,
        ),
    ]
