# Generated by Django 6.0.3 on 2026-04-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='adventure_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adventure',
            name='key_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='adventure',
            name='published_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='smart_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_challenge_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_geofencing_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_is_final',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='al_key_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ALJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_message', models.TextField(blank=True)),
                ('journal_image_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geocache', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='al_journal', to='geocaches.geocache')),
            ],
        ),
    ]
