# Generated by Django 6.0.3 on 2026-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0003_alstagedetal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='median_time_to_complete',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
