# Generated by Django 6.0.3 on 2026-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0005_move_stage_fields_to_alstagedetal'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='is_highly_recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='owner_public_guid',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='adventure',
            name='ratings_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='ratings_total_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alstagedetail',
            name='answer_code_hashes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
