# Generated by Django 6.0.3 on 2026-04-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0006_alc_ratings_recommended_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField(db_index=True)),
                ('player_username', models.CharField(blank=True, max_length=255)),
                ('player_public_guid', models.CharField(blank=True, max_length=36)),
                ('player_avatar_url', models.TextField(blank=True)),
                ('player_geocache_find_count', models.PositiveIntegerField(blank=True, null=True)),
                ('player_completed_adventure_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True)),
                ('recommended', models.BooleanField(default=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('adventure_completed_utc', models.DateTimeField(blank=True, null=True)),
                ('created_utc', models.DateTimeField()),
                ('modified_utc', models.DateTimeField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_reviews', to='geocaches.adventure')),
            ],
            options={
                'ordering': ['-created_utc'],
                'unique_together': {('adventure', 'review_id')},
            },
        ),
    ]
