# Generated by Django 6.0.4 on 2026-05-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0009_builtin_alc_in_progress_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('travel_bug', 'Travel Bug'), ('geocoin', 'Geocoin'), ('other', 'Other')], default='travel_bug', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_gc_id', models.IntegerField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('goal', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('is_collectible', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('holder_state', models.CharField(choices=[('unknown', 'Unknown'), ('in_cache', 'In a cache'), ('held_by_user', 'In my inventory'), ('held_by_other', 'Held by someone else'), ('collection', 'In my collection'), ('missing', 'Missing')], default='unknown', max_length=20)),
                ('current_geocache_code', models.CharField(blank=True, max_length=20)),
                ('current_geocache_name', models.CharField(blank=True, max_length=255)),
                ('current_holder_name', models.CharField(blank=True, max_length=255)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('coords_user_override', models.BooleanField(default=False)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('total_visits', models.IntegerField(blank=True, null=True)),
                ('last_log_date', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_geocache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackables_here', to='geocaches.geocache')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('Discovered It', 'Discovered It'), ('Retrieve It from a Cache', 'Retrieved It'), ('Dropped Off', 'Dropped Off'), ('Grab It (Not from a Cache)', 'Grabbed It'), ('Write note', 'Write Note'), ('Visited', 'Visited'), ('Mark Missing', 'Mark Missing'), ('Move to Collection', 'Move to Collection'), ('Move to Inventory', 'Move to Inventory')], max_length=50)),
                ('logged_date', models.DateField()),
                ('logged_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('geocache_ref_code', models.CharField(blank=True, max_length=20)),
                ('geocache_lat', models.FloatField(blank=True, null=True)),
                ('geocache_lon', models.FloatField(blank=True, null=True)),
                ('source_id', models.CharField(blank=True, max_length=50)),
                ('is_local', models.BooleanField(default=False)),
                ('geocache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackable_logs', to='geocaches.geocache')),
                ('trackable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='geocaches.trackable')),
            ],
            options={
                'ordering': ['-logged_at', '-logged_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('trackable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geocaches.trackable')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geocaches.trackablelog')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CacheTrackableMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_id', models.IntegerField(blank=True, null=True)),
                ('ref_code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackable_mentions', to='geocaches.geocache')),
            ],
            options={
                'ordering': ['ref_code'],
                'unique_together': {('geocache', 'ref_code')},
            },
        ),
    ]
