# Generated by Django 6.0.4 on 2026-05-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0010_trackable_trackablelog_trackableimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackable',
            name='auto_visit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackable',
            name='auto_visit_text',
            field=models.TextField(blank=True),
        ),
    ]
