# Generated by Django 6.0.4 on 2026-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0011_trackable_auto_visit_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackableimage',
            options={'ordering': ['-uploaded_at', 'id']},
        ),
        migrations.AddField(
            model_name='trackableimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackableimage',
            name='large_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trackableimage',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackableimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='trackableimage',
            constraint=models.UniqueConstraint(condition=models.Q(('trackable__isnull', False), models.Q(('source_id', ''), _negated=True)), fields=('trackable', 'source_id'), name='trackableimage_unique_source_per_trackable'),
        ),
    ]
