# Generated by Django 6.0.4 on 2026-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0012_alter_trackableimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tb_icon', 'Trackable icon'), ('tb_listing', 'Trackable listing image'), ('tb_log', 'Trackable log image'), ('cache_listing', 'Cache listing image'), ('cache_log', 'Cache log image'), ('alc', 'Adventure Lab image')], db_index=True, max_length=20)),
                ('source_url', models.URLField(max_length=1024)),
                ('filename', models.CharField(max_length=128)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'downloaded_at'], name='geocaches_c_categor_de3373_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'source_url'), name='cached_image_unique_category_url')],
            },
        ),
    ]
