# Generated by Django 6.0.4 on 2026-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0015_extend_image_cache_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedimage',
            name='linked_adventures',
            field=models.ManyToManyField(blank=True, related_name='cached_images_in', to='geocaches.adventure'),
        ),
        migrations.AddField(
            model_name='cachedimage',
            name='linked_geocaches',
            field=models.ManyToManyField(blank=True, related_name='cached_images_in', to='geocaches.geocache'),
        ),
        migrations.AddField(
            model_name='cachedimage',
            name='linked_logs',
            field=models.ManyToManyField(blank=True, related_name='cached_images_in', to='geocaches.log'),
        ),
        migrations.AddField(
            model_name='cachedimage',
            name='linked_trackable_logs',
            field=models.ManyToManyField(blank=True, related_name='cached_images_in', to='geocaches.trackablelog'),
        ),
        migrations.AddField(
            model_name='cachedimage',
            name='linked_trackables',
            field=models.ManyToManyField(blank=True, related_name='cached_images_in', to='geocaches.trackable'),
        ),
    ]
