# Generated by Django 6.0.4 on 2026-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0016_cached_image_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackable',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trackables', to='geocaches.tag'),
        ),
    ]
