# Generated by Django 6.0.4 on 2026-05-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0017_trackable_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('gc', 'Geocaching.com'), ('oc', 'Opencaching')], max_length=16)),
                ('oc_platform', models.CharField(blank=True, default='', max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Unpublished', 'Unpublished'), ('Active', 'Active'), ('Disabled', 'Disabled'), ('Locked', 'Locked'), ('Archived', 'Archived')], default='', max_length=16)),
                ('last_status_refresh', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='geocaches_i_code_799a37_idx'), models.Index(fields=['source', 'oc_platform'], name='geocaches_i_source_363fdd_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'oc_platform', 'code'), name='uniq_ignore_entry')],
            },
        ),
    ]
