# Generated by Django 6.0.4 on 2026-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0018_ignore_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignorelistentry',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('gsak', 'GSAK Import'), ('gc', 'Geocaching.com'), ('oc', 'Opencaching')], max_length=16),
        ),
    ]
