# Generated by Django 6.0.4 on 2026-05-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0019_ignore_source_gsak'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='map_hidden_always',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
