# Generated by Django 6.0.4 on 2026-05-22 15:05
# Hand-edited to add a data backfill step.

from django.db import migrations, models


def _backfill_tree_from_params(apps, schema_editor):
    """Convert every SavedFilter.params into a tree JSON via the legacy shim.

    Pre-existing saved filters were stored as URL-param dicts.  After this
    migration they also carry an equivalent ``tree`` payload so the new
    ``?f=<name>`` URL resolution can route through the v2 filter expression
    compiler.  Builtin filters whose ``params`` shape isn't recognised by
    the shim get an empty tree (root AND with no children) — they continue
    to work through their ``params`` path until the dialog rewrite.
    """
    from geocaches.filter_expr import legacy_params_to_tree

    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    for sf in SavedFilter.objects.all():
        params = sf.params or {}
        try:
            tree = legacy_params_to_tree(params)
            sf.tree = tree.to_dict()
        except Exception:
            # If shim can't handle the shape (e.g. odd builtin), leave
            # tree NULL so ?f= falls back to params-based resolution.
            sf.tree = None
        sf.save(update_fields=["tree"])


def _clear_tree(apps, schema_editor):
    SavedFilter = apps.get_model("geocaches", "SavedFilter")
    SavedFilter.objects.update(tree=None)


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0022_geocache_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilter',
            name='tree',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_tree_from_params, _clear_tree),
    ]
