# Generated by Django 6.0.4 on 2026-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0024_savedfilter_drop_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='manual_location',
            field=models.BooleanField(default=False),
        ),
    ]
