# Generated by Django 6.0.4 on 2026-05-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0025_geocache_manual_location'),
        ('preferences', '0004_logtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gc', 'Geocaching.com')], default='gc', max_length=8)),
                ('server_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.PositiveSmallIntegerField(default=20)),
                ('cache_type_id', models.PositiveIntegerField()),
                ('log_event_ids', models.JSONField(default=list)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('server_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_notifications', to='preferences.referencepoint')),
            ],
            options={
                'ordering': ['location__name', 'name', 'cache_type_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('server_id__gt', '')), fields=('source', 'server_id'), name='uniq_notification_server_id')],
            },
        ),
    ]
