# Generated by Django 6.0.4 on 2026-05-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0026_gcnotification'),
        ('preferences', '0004_logtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('oc_de', 'opencaching.de'), ('oc_pl', 'opencaching.pl'), ('oc_uk', 'opencaching.uk'), ('oc_nl', 'opencaching.nl')], max_length=8, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.PositiveSmallIntegerField(default=20)),
                ('enabled', models.BooleanField(default=True)),
                ('notify_oconly', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_notifications', to='preferences.referencepoint')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
    ]
