# Generated by Django 6.0.4 on 2026-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0027_ocnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocnotification',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Once per hour'), ('daily', 'Once per day'), ('weekly', 'Once per week')], default='daily', max_length=8),
        ),
        migrations.AddField(
            model_name='ocnotification',
            name='notify_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ocnotification',
            name='platform',
            field=models.CharField(choices=[('oc_de', 'opencaching.de'), ('oc_pl', 'opencaching.pl'), ('oc_uk', 'opencaching.uk'), ('oc_nl', 'opencaching.nl'), ('oc_us', 'opencaching.us')], max_length=8, unique=True),
        ),
    ]
