# Generated by Django 6.0.4 on 2026-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0028_ocnotification_frequency_ocnotification_notify_logs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocnotification',
            options={'ordering': ['platform', 'server_id']},
        ),
        migrations.AddField(
            model_name='ocnotification',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ocnotification',
            name='server_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='ocnotification',
            name='platform',
            field=models.CharField(choices=[('oc_de', 'opencaching.de'), ('oc_pl', 'opencaching.pl'), ('oc_uk', 'opencaching.uk'), ('oc_nl', 'opencaching.nl'), ('oc_us', 'opencaching.us')], max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='ocnotification',
            unique_together={('platform', 'server_id')},
        ),
    ]
