# Generated by Django 6.0.4 on 2026-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0032_souvenir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocnotification',
            name='platform',
            field=models.CharField(choices=[('oc_de', 'opencaching.de'), ('oc_pl', 'opencaching.pl'), ('oc_uk', 'opencache.uk'), ('oc_nl', 'opencaching.nl'), ('oc_us', 'opencaching.us')], max_length=8),
        ),
    ]
