# Generated by Django 6.0.4 on 2026-06-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0034_souvenir_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField(help_text='gc.com collection id', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('found', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('premium_only', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('criteria_url', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_completed', '-found', 'name'],
            },
        ),
    ]
