# Generated by Django 6.0.4 on 2026-06-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0035_treasure_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('event', 'Event'), ('missing_day', 'Missing day')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('cache_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geocache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='geocaches.geocache')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
