# Generated by Django 6.0.4 on 2026-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0036_calendarentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='tz_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
