# Generated by Django 6.0.4 on 2026-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0037_calendarentry_alarm_calendarentry_tz_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geocache',
            index=models.Index(fields=['latitude', 'longitude'], name='geocache_lat_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='geocache',
            index=models.Index(fields=['deleted_at'], name='geocache_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='geocache',
            index=models.Index(fields=['found'], name='geocache_found_idx'),
        ),
        migrations.AddIndex(
            model_name='geocache',
            index=models.Index(fields=['completed'], name='geocache_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='geocache',
            index=models.Index(fields=['cache_type'], name='geocache_cache_type_idx'),
        ),
        migrations.AddIndex(
            model_name='geocache',
            index=models.Index(fields=['status'], name='geocache_status_idx'),
        ),
    ]
