# Generated by Django 6.0.4 on 2026-06-14 19:04

from django.db import migrations, models


def deduplicate_logs_and_images(apps, schema_editor):
    """Delete duplicate rows before adding unique constraints.

    For Log: keep the lowest pk per (geocache_id, source_id) group where
    source_id is non-empty.
    For Image: keep the lowest pk per (geocache_id, url) group.
    """
    Log = apps.get_model("geocaches", "Log")
    Image = apps.get_model("geocaches", "Image")

    # Deduplicate logs with non-empty source_id
    seen = {}
    for log in (
        Log.objects.exclude(source_id="")
        .order_by("geocache_id", "source_id", "pk")
        .values_list("pk", "geocache_id", "source_id")
    ):
        pk, geocache_id, source_id = log
        key = (geocache_id, source_id)
        if key in seen:
            Log.objects.filter(pk=pk).delete()
        else:
            seen[key] = pk

    # Deduplicate images by (geocache_id, url)
    seen = {}
    for img in (
        Image.objects.order_by("geocache_id", "url", "pk")
        .values_list("pk", "geocache_id", "url")
    ):
        pk, geocache_id, url = img
        key = (geocache_id, url)
        if key in seen:
            Image.objects.filter(pk=pk).delete()
        else:
            seen[key] = pk


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0038_add_geocache_indexes'),
    ]

    operations = [
        migrations.RunPython(deduplicate_logs_and_images, noop),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('geocache', 'url'), name='uniq_image_geocache_url'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('geocache', 'source_id'), name='uniq_log_geocache_source_id'),
        ),
    ]
