# Generated by Django 6.0.4 on 2026-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0039_dedup_log_image_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('waypoints', models.JSONField()),
                ('profile', models.CharField(default='hiking-beta', max_length=40)),
                ('width_m', models.IntegerField(default=1000)),
                ('path', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
