# Generated by Django 6.0.6 on 2026-09-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0040_savedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='alstagedetail',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
