# Generated by Django 6.0.6 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0041_alstagedetail_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='found_accuracy',
            field=models.CharField(blank=True, choices=[('app_verified', 'App-verified'), ('visited_same_day', 'Visited — logged same day'), ('visited_different_day', 'Visited — logged different day'), ('armchair', 'Armchair (not visited)')], default='', max_length=25),
        ),
    ]
