# Generated by Django 6.0.6 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0042_geocache_found_accuracy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['log_type', 'user_id'], name='log_log_type_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['geocache', 'logged_date'], name='log_geocache_logged_date_idx'),
        ),
    ]
