# Generated by Django 6.0.6 on 2026-09-11 11:37

from django.db import migrations, models


def check_no_duplicate_codes(apps, schema_editor):
    """Refuse the migration while two caches outside the Trash share a code.

    Nothing is changed here: the constraints below simply cannot be created
    while duplicates exist, and failing with the list of offenders is far more
    useful than SQLite's bare "UNIQUE constraint failed".
    """
    from geocaches.services.codes import find_duplicate_live_codes, format_duplicate_report

    duplicates = find_duplicate_live_codes(schema_editor.connection)
    if not duplicates:
        return

    total = sum(len(rows) for rows in duplicates.values())
    raise RuntimeError(
        f"GCForge cannot enforce unique cache codes yet: {total} code(s) are used by "
        "more than one cache that is not in the Trash.\n\n"
        f"{format_duplicate_report(duplicates)}\n\n"
        "Your database has NOT been changed. Resolve the duplicates, then start "
        "GCForge again:\n"
        "  * Tools -> Find duplicates merges a GC/OC pair into one record.\n"
        "  * Or open each id listed above in the cache list and delete the surplus\n"
        "    record. Moving it to the Trash is enough - trashed caches are allowed\n"
        "    to keep a code that a live cache also uses.\n"
        "  * 'python manage.py find_duplicate_codes' prints this list again at any time."
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('geocaches', '0043_add_log_indexes'),
    ]

    operations = [
        migrations.RunPython(check_no_duplicate_codes, noop),
        migrations.AddConstraint(
            model_name='geocache',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('gc_code', ''), _negated=True)), fields=('gc_code',), name='uniq_live_gc_code'),
        ),
        migrations.AddConstraint(
            model_name='geocache',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('oc_code', ''), _negated=True)), fields=('oc_code',), name='uniq_live_oc_code'),
        ),
        migrations.AddConstraint(
            model_name='geocache',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('al_code', ''), _negated=True)), fields=('al_code',), name='uniq_live_al_code'),
        ),
    ]
